import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs/promises"; // <-- 新增: 导入Node.js文件系统模块 (异步)
import path from "path";       // <-- 新增: 导入Node.js路径模块
import fsSync from "fs";       // <-- 新增: 导入Node.js文件系统模块 (用于'watch')

// import { sassPlugin } from "esbuild-sass-plugin";

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const distDir = "dist"; // <-- 新增: 定义我们的输出目录

// --- 封装一个复制 manifest.json 的函数 ---
const copyManifest = async () => {
	try {
		// 确保 dist 目录存在
		await fs.mkdir(distDir, { recursive: true });
		// 复制 manifest.json
		await fs.copyFile("manifest.json", path.join(distDir, "manifest.json"));
		// 仅在开发模式下打印日志，保持生产模式简洁
		if (!prod) {
			console.log("Copied manifest.json to dist/");
		}
	} catch (err) {
		console.error("Error copying manifest.json:", err);
	}
};

// --- 1. CSS 打包任务 ---
const cssContext = await esbuild.context({
	entryPoints: ["src/styles.css"],
	bundle: true,
	outfile: path.join(distDir, "styles.css"), // <-- 修改: 输出到 dist/styles.css
	minify: prod,
	// ... (SCSS 选项)
});

// --- 2. TS 打包任务 ---
const tsContext = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: path.join(distDir, "main.js"), // <-- 修改: 输出到 dist/main.js
	minify: prod,
});

// --- 3. 修改 "watch" 和 "build" 逻辑 ---
if (prod) {
	// 生产模式: 打包所有三个文件然后退出
	await Promise.all([
		tsContext.rebuild(),
		cssContext.rebuild(),
		copyManifest() // <-- 新增: 复制 manifest
	]);
	console.log("Build complete. Output in /dist");
	process.exit(0);
} else {
	// 开发模式: 监视所有三个文件

	// 启动时先复制一次 manifest
	await copyManifest();

	// 监视 TS 和 CSS
	await Promise.all([
		tsContext.watch(),
		cssContext.watch()
	]);

	// <-- 新增: 单独监视 manifest.json 的变化
	fsSync.watch("manifest.json", (event, filename) => {
		if (event === "change") {
			// 如果 manifest.json 变了, 重新复制它
			copyManifest();
		}
	});

	console.log("Watching for changes... Outputting to /dist");
}
